---
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.PJTquQRighsqGHTo8HUwz5Nx.k5HJti"
  reserved: true
  backend_roles:
    - "admin"
  description: "Demo admin user"

kibanaserver:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.PJTquQRighsqGHTo8HUwz5Nx.k5HJti"
  reserved: true
  description: "Demo kibanaserver user"
